use_frameworks!

platform :ios, '8.0'

target 'SYZNumberCollectionKit_Example' do
  pod 'SYZNumberCollectionKit', :path => '../'

  target 'SYZNumberCollectionKit_Tests' do
    inherit! :search_paths

  end
end
